
export default [
    {
        "id" : 1,
        "combat_rating" : "0",
        "proficiencybonus" : 2,
        "armorclasssuggestion" : "<=13",
        "armorclassstartingpoint" : 13,
        "hitpointssuggestion" : "1-6",
        "hitpointsmin" : 1,
        "hitpointsmax" : 6,
        "attackbonussuggestion" : "<=3",
        "attackbonus" : 3,
        "damageperroundsuggestion" : "0-1",
        "savedcsuggestion" : "<=13",
        "savedc" : 13
    },
    {
        "id" : 2,
        "combat_rating" : "1\/8",
        "proficiencybonus" : 2,
        "armorclasssuggestion" : "13",
        "armorclassstartingpoint" : 13,
        "hitpointssuggestion" : "7-35",
        "hitpointsmin" : 7,
        "hitpointsmax" : 35,
        "attackbonussuggestion" : "3",
        "attackbonus" : 3,
        "damageperroundsuggestion" : "2-3",
        "savedcsuggestion" : "13",
        "savedc" : 13
    },
    {
        "id" : 3,
        "combat_rating" : "1\/4",
        "proficiencybonus" : 2,
        "armorclasssuggestion" : "13",
        "armorclassstartingpoint" : 13,
        "hitpointssuggestion" : "36-49",
        "hitpointsmin" : 36,
        "hitpointsmax" : 49,
        "attackbonussuggestion" : "3",
        "attackbonus" : 3,
        "damageperroundsuggestion" : "4-5",
        "savedcsuggestion" : "13",
        "savedc" : 13
    },
    {
        "id" : 4,
        "combat_rating" : "1\/2",
        "proficiencybonus" : 2,
        "armorclasssuggestion" : "13",
        "armorclassstartingpoint" : 13,
        "hitpointssuggestion" : "50-70",
        "hitpointsmin" : 50,
        "hitpointsmax" : 70,
        "attackbonussuggestion" : "3",
        "attackbonus" : 3,
        "damageperroundsuggestion" : "6-8",
        "savedcsuggestion" : "13",
        "savedc" : 13
    },
    {
        "id" : 5,
        "combat_rating" : "1",
        "proficiencybonus" : 2,
        "armorclasssuggestion" : "13",
        "armorclassstartingpoint" : 13,
        "hitpointssuggestion" : "71-85",
        "hitpointsmin" : 71,
        "hitpointsmax" : 85,
        "attackbonussuggestion" : "3",
        "attackbonus" : 3,
        "damageperroundsuggestion" : "9-14",
        "savedcsuggestion" : "13",
        "savedc" : 13
    },
    {
        "id" : 6,
        "combat_rating" : "2",
        "proficiencybonus" : 2,
        "armorclasssuggestion" : "13",
        "armorclassstartingpoint" : 13,
        "hitpointssuggestion" : "86-100",
        "hitpointsmin" : 86,
        "hitpointsmax" : 100,
        "attackbonussuggestion" : "3",
        "attackbonus" : 3,
        "damageperroundsuggestion" : "15-20",
        "savedcsuggestion" : "13",
        "savedc" : 13
    },
    {
        "id" : 7,
        "combat_rating" : "3",
        "proficiencybonus" : 2,
        "armorclasssuggestion" : "13",
        "armorclassstartingpoint" : 13,
        "hitpointssuggestion" : "101-115",
        "hitpointsmin" : 101,
        "hitpointsmax" : 115,
        "attackbonussuggestion" : "4",
        "attackbonus" : 4,
        "damageperroundsuggestion" : "21-26",
        "savedcsuggestion" : "13",
        "savedc" : 13
    },
    {
        "id" : 8,
        "combat_rating" : "4",
        "proficiencybonus" : 2,
        "armorclasssuggestion" : "14",
        "armorclassstartingpoint" : 14,
        "hitpointssuggestion" : "116-130",
        "hitpointsmin" : 116,
        "hitpointsmax" : 130,
        "attackbonussuggestion" : "5",
        "attackbonus" : 5,
        "damageperroundsuggestion" : "27-32",
        "savedcsuggestion" : "14",
        "savedc" : 14
    },
    {
        "id" : 9,
        "combat_rating" : "5",
        "proficiencybonus" : 3,
        "armorclasssuggestion" : "15",
        "armorclassstartingpoint" : 15,
        "hitpointssuggestion" : "131-145",
        "hitpointsmin" : 131,
        "hitpointsmax" : 145,
        "attackbonussuggestion" : "6",
        "attackbonus" : 6,
        "damageperroundsuggestion" : "33-38",
        "savedcsuggestion" : "15",
        "savedc" : 15
    },
    {
        "id" : 10,
        "combat_rating" : "6",
        "proficiencybonus" : 3,
        "armorclasssuggestion" : "15",
        "armorclassstartingpoint" : 15,
        "hitpointssuggestion" : "146-160",
        "hitpointsmin" : 146,
        "hitpointsmax" : 160,
        "attackbonussuggestion" : "6",
        "attackbonus" : 6,
        "damageperroundsuggestion" : "39-44",
        "savedcsuggestion" : "15",
        "savedc" : 15
    },
    {
        "id" : 11,
        "combat_rating" : "7",
        "proficiencybonus" : 3,
        "armorclasssuggestion" : "15",
        "armorclassstartingpoint" : 15,
        "hitpointssuggestion" : "161-175",
        "hitpointsmin" : 161,
        "hitpointsmax" : 175,
        "attackbonussuggestion" : "6",
        "attackbonus" : 6,
        "damageperroundsuggestion" : "45-50",
        "savedcsuggestion" : "15",
        "savedc" : 15
    },
    {
        "id" : 12,
        "combat_rating" : "8",
        "proficiencybonus" : 3,
        "armorclasssuggestion" : "16",
        "armorclassstartingpoint" : 16,
        "hitpointssuggestion" : "176-190",
        "hitpointsmin" : 176,
        "hitpointsmax" : 190,
        "attackbonussuggestion" : "7",
        "attackbonus" : 7,
        "damageperroundsuggestion" : "51-56",
        "savedcsuggestion" : "16",
        "savedc" : 16
    },
    {
        "id" : 13,
        "combat_rating" : "9",
        "proficiencybonus" : 4,
        "armorclasssuggestion" : "16",
        "armorclassstartingpoint" : 16,
        "hitpointssuggestion" : "191-205",
        "hitpointsmin" : 191,
        "hitpointsmax" : 205,
        "attackbonussuggestion" : "7",
        "attackbonus" : 7,
        "damageperroundsuggestion" : "57-62",
        "savedcsuggestion" : "16",
        "savedc" : 16
    },
    {
        "id" : 14,
        "combat_rating" : "10",
        "proficiencybonus" : 4,
        "armorclasssuggestion" : "17",
        "armorclassstartingpoint" : 17,
        "hitpointssuggestion" : "206-220",
        "hitpointsmin" : 206,
        "hitpointsmax" : 220,
        "attackbonussuggestion" : "7",
        "attackbonus" : 7,
        "damageperroundsuggestion" : "63-68",
        "savedcsuggestion" : "16",
        "savedc" : 16
    },
    {
        "id" : 15,
        "combat_rating" : "11",
        "proficiencybonus" : 4,
        "armorclasssuggestion" : "17",
        "armorclassstartingpoint" : 17,
        "hitpointssuggestion" : "221-235",
        "hitpointsmin" : 221,
        "hitpointsmax" : 235,
        "attackbonussuggestion" : "8",
        "attackbonus" : 8,
        "damageperroundsuggestion" : "69-74",
        "savedcsuggestion" : "17",
        "savedc" : 17
    },
    {
        "id" : 16,
        "combat_rating" : "12",
        "proficiencybonus" : 4,
        "armorclasssuggestion" : "17",
        "armorclassstartingpoint" : 17,
        "hitpointssuggestion" : "236-250",
        "hitpointsmin" : 236,
        "hitpointsmax" : 250,
        "attackbonussuggestion" : "8",
        "attackbonus" : 8,
        "damageperroundsuggestion" : "75-80",
        "savedcsuggestion" : "17",
        "savedc" : 17
    },
    {
        "id" : 17,
        "combat_rating" : "13",
        "proficiencybonus" : 5,
        "armorclasssuggestion" : "18",
        "armorclassstartingpoint" : 18,
        "hitpointssuggestion" : "251-265",
        "hitpointsmin" : 252,
        "hitpointsmax" : 265,
        "attackbonussuggestion" : "8",
        "attackbonus" : 8,
        "damageperroundsuggestion" : "81-86",
        "savedcsuggestion" : "18",
        "savedc" : 18
    },
    {
        "id" : 18,
        "combat_rating" : "14",
        "proficiencybonus" : 5,
        "armorclasssuggestion" : "18",
        "armorclassstartingpoint" : 18,
        "hitpointssuggestion" : "266-280",
        "hitpointsmin" : 266,
        "hitpointsmax" : 280,
        "attackbonussuggestion" : "8",
        "attackbonus" : 8,
        "damageperroundsuggestion" : "87-92",
        "savedcsuggestion" : "18",
        "savedc" : 18
    },
    {
        "id" : 19,
        "combat_rating" : "15",
        "proficiencybonus" : 5,
        "armorclasssuggestion" : "18",
        "armorclassstartingpoint" : 18,
        "hitpointssuggestion" : "281-295",
        "hitpointsmin" : 281,
        "hitpointsmax" : 295,
        "attackbonussuggestion" : "8",
        "attackbonus" : 8,
        "damageperroundsuggestion" : "93-98",
        "savedcsuggestion" : "18",
        "savedc" : 18
    },
    {
        "id" : 20,
        "combat_rating" : "16",
        "proficiencybonus" : 5,
        "armorclasssuggestion" : "18",
        "armorclassstartingpoint" : 18,
        "hitpointssuggestion" : "296-310",
        "hitpointsmin" : 296,
        "hitpointsmax" : 310,
        "attackbonussuggestion" : "9",
        "attackbonus" : 9,
        "damageperroundsuggestion" : "99-104",
        "savedcsuggestion" : "18",
        "savedc" : 18
    },
    {
        "id" : 21,
        "combat_rating" : "17",
        "proficiencybonus" : 6,
        "armorclasssuggestion" : "19",
        "armorclassstartingpoint" : 19,
        "hitpointssuggestion" : "311-325",
        "hitpointsmin" : 311,
        "hitpointsmax" : 325,
        "attackbonussuggestion" : "10",
        "attackbonus" : 10,
        "damageperroundsuggestion" : "105-110",
        "savedcsuggestion" : "19",
        "savedc" : 19
    },
    {
        "id" : 22,
        "combat_rating" : "18",
        "proficiencybonus" : 6,
        "armorclasssuggestion" : "19",
        "armorclassstartingpoint" : 19,
        "hitpointssuggestion" : "326-340",
        "hitpointsmin" : 326,
        "hitpointsmax" : 340,
        "attackbonussuggestion" : "10",
        "attackbonus" : 10,
        "damageperroundsuggestion" : "111-116",
        "savedcsuggestion" : "19",
        "savedc" : 19
    },
    {
        "id" : 23,
        "combat_rating" : "19",
        "proficiencybonus" : 6,
        "armorclasssuggestion" : "19",
        "armorclassstartingpoint" : 19,
        "hitpointssuggestion" : "341-355",
        "hitpointsmin" : 341,
        "hitpointsmax" : 355,
        "attackbonussuggestion" : "10",
        "attackbonus" : 10,
        "damageperroundsuggestion" : "117-122",
        "savedcsuggestion" : "19",
        "savedc" : 19
    },
    {
        "id" : 24,
        "combat_rating" : "20",
        "proficiencybonus" : 6,
        "armorclasssuggestion" : "19",
        "armorclassstartingpoint" : 19,
        "hitpointssuggestion" : "356-400",
        "hitpointsmin" : 356,
        "hitpointsmax" : 400,
        "attackbonussuggestion" : "10",
        "attackbonus" : 10,
        "damageperroundsuggestion" : "123-140",
        "savedcsuggestion" : "19",
        "savedc" : 19
    },
    {
        "id" : 25,
        "combat_rating" : "21",
        "proficiencybonus" : 7,
        "armorclasssuggestion" : "19",
        "armorclassstartingpoint" : 19,
        "hitpointssuggestion" : "401-445",
        "hitpointsmin" : 401,
        "hitpointsmax" : 445,
        "attackbonussuggestion" : "11",
        "attackbonus" : 11,
        "damageperroundsuggestion" : "141-158",
        "savedcsuggestion" : "20",
        "savedc" : 20
    },
    {
        "id" : 26,
        "combat_rating" : "22",
        "proficiencybonus" : 7,
        "armorclasssuggestion" : "19",
        "armorclassstartingpoint" : 19,
        "hitpointssuggestion" : "446-490",
        "hitpointsmin" : 446,
        "hitpointsmax" : 490,
        "attackbonussuggestion" : "11",
        "attackbonus" : 11,
        "damageperroundsuggestion" : "159-176",
        "savedcsuggestion" : "20",
        "savedc" : 20
    },
    {
        "id" : 27,
        "combat_rating" : "23",
        "proficiencybonus" : 7,
        "armorclasssuggestion" : "19",
        "armorclassstartingpoint" : 19,
        "hitpointssuggestion" : "491-535",
        "hitpointsmin" : 491,
        "hitpointsmax" : 535,
        "attackbonussuggestion" : "11",
        "attackbonus" : 11,
        "damageperroundsuggestion" : "177-194",
        "savedcsuggestion" : "20",
        "savedc" : 20
    },
    {
        "id" : 28,
        "combat_rating" : "24",
        "proficiencybonus" : 7,
        "armorclasssuggestion" : "19",
        "armorclassstartingpoint" : 19,
        "hitpointssuggestion" : "536-580",
        "hitpointsmin" : 536,
        "hitpointsmax" : 580,
        "attackbonussuggestion" : "12",
        "attackbonus" : 12,
        "damageperroundsuggestion" : "195-212",
        "savedcsuggestion" : "21",
        "savedc" : 21
    },
    {
        "id" : 29,
        "combat_rating" : "25",
        "proficiencybonus" : 8,
        "armorclasssuggestion" : "19",
        "armorclassstartingpoint" : 19,
        "hitpointssuggestion" : "581-625",
        "hitpointsmin" : 581,
        "hitpointsmax" : 625,
        "attackbonussuggestion" : "12",
        "attackbonus" : 12,
        "damageperroundsuggestion" : "213-230",
        "savedcsuggestion" : "21",
        "savedc" : 21
    },
    {
        "id" : 30,
        "combat_rating" : "26",
        "proficiencybonus" : 8,
        "armorclasssuggestion" : "19",
        "armorclassstartingpoint" : 19,
        "hitpointssuggestion" : "626-670",
        "hitpointsmin" : 626,
        "hitpointsmax" : 670,
        "attackbonussuggestion" : "12",
        "attackbonus" : 12,
        "damageperroundsuggestion" : "231-248",
        "savedcsuggestion" : "21",
        "savedc" : 21
    },
    {
        "id" : 31,
        "combat_rating" : "27",
        "proficiencybonus" : 8,
        "armorclasssuggestion" : "19",
        "armorclassstartingpoint" : 19,
        "hitpointssuggestion" : "671-715",
        "hitpointsmin" : 671,
        "hitpointsmax" : 715,
        "attackbonussuggestion" : "13",
        "attackbonus" : 13,
        "damageperroundsuggestion" : "249-266",
        "savedcsuggestion" : "22",
        "savedc" : 22
    },
    {
        "id" : 32,
        "combat_rating" : "28",
        "proficiencybonus" : 8,
        "armorclasssuggestion" : "19",
        "armorclassstartingpoint" : 19,
        "hitpointssuggestion" : "716-760",
        "hitpointsmin" : 716,
        "hitpointsmax" : 760,
        "attackbonussuggestion" : "13",
        "attackbonus" : 13,
        "damageperroundsuggestion" : "267-284",
        "savedcsuggestion" : "22",
        "savedc" : 22
    },
    {
        "id" : 33,
        "combat_rating" : "29",
        "proficiencybonus" : 9,
        "armorclasssuggestion" : "19",
        "armorclassstartingpoint" : 19,
        "hitpointssuggestion" : "761-805",
        "hitpointsmin" : 761,
        "hitpointsmax" : 805,
        "attackbonussuggestion" : "14",
        "attackbonus" : 14,
        "damageperroundsuggestion" : "285-302",
        "savedcsuggestion" : "22",
        "savedc" : 22
    },
    {
        "id" : 34,
        "combat_rating" : "30",
        "proficiencybonus" : 9,
        "armorclasssuggestion" : "19",
        "armorclassstartingpoint" : 19,
        "hitpointssuggestion" : "806-850",
        "hitpointsmin" : 805,
        "hitpointsmax" : 850,
        "attackbonussuggestion" : "14",
        "attackbonus" : 14,
        "damageperroundsuggestion" : "303-320",
        "savedcsuggestion" : "23",
        "savedc" : 23
    },
    {
        "id" : 35,
        "combat_rating" : "31",
        "proficiencybonus" : 10,
        "armorclasssuggestion" : "20",
        "armorclassstartingpoint" : 20,
        "hitpointssuggestion" : "851-900",
        "hitpointsmin" : 851,
        "hitpointsmax" : 900,
        "attackbonussuggestion" : "15",
        "attackbonus" : 15,
        "damageperroundsuggestion" : "321-350",
        "savedcsuggestion" : "24",
        "savedc" : 24
    }
]
